### ISSUE TITLE
Possible to add a superspeed USB C DRD, like dwc3

### ISSUE THREAD

**Issue by berlin4apk** [v3l0c1r4pt0r/ucm4#12]
Possible to add a superspeed USB C DRD, like dwc3?

So we can power the cm4 from a USB C host, and with  gedged devices act as a offline / caching ipxe server, to install the host

**Comment by v3l0c1r4pt0r** [comment]
I'm not sure if I understood you correctly. DRD is equivalent of USB-OTG that was introduced in USB 3.0. SoC on Raspberry Pi does not support USB 3.0 and never did - on Pi 4 it is separate chip that does that. But if what you want is USB gadget, then probably it is still possible. With my board I used the same USB connector that delivers power to communicate with rpiboot bootloader in slave mode from RPi perspective. The other way should also be possible with OTG.
