### ISSUE TITLE
The submodule of `devel` branch had been deleted

### ISSUE THREAD

**Issue by hellodword** [v3l0c1r4pt0r/ucm4#13]
[kicad-randoms @ e5ce080](https://github.com/v3l0c1r4pt0r/kicad-randoms/tree/e5ce08036673cda52184c84115a843a67bdb7c96)

BTW, thanks for your amazing work, I love it.

**Comment by v3l0c1r4pt0r** [comment]
Not deleted, but I forgot to push it :) Thanks for noticing.
